Feature/filter saved recipes
jalbe0076/whats-cooking pull request #30
Opened 2023-05-21 21:29 UTC by paulina-isabel

### What is the feature?
Adding a filter for tags in saved recipes.

### How you implemented the solution?
Added a new dropdown menu in the saved recipes page view.
Called populateTags in savedViewBtn event listener to load the saved recipe tags in dropdown.
Added an else statement in the conditional inside viewSavedRecipes to hide the dropdown when the user has no saved recipes available.
When a saved recipe is deleted from saved recipes, its tags get deleted from the dropdown.

### Any changes in the UI (Screenshots)?
![ezgif com-video-to-gif (4)](https://github.com/jalbe0076/whats-cooking/assets/123966150/a348ff17-c796-4b29-b038-00e58d2d7180)

2023-05-21 21:33 UTC, alivaditis approved these changes
awesome job!!

2023-05-21 22:46 UTC, jalbe0076 requested changes
Minor change, we just need to delete the user data file to meet the comp specs

2023-05-21 22:46 UTC, jalbe0076 commented on src/data/users.js
This file needs to stay deleted as we're now fetching API's

2023-05-21 23:24 UTC, paulina-isabel commented on src/data/users.js
All done! Good catch.

2023-05-22 00:57 UTC, CaliHam approved these changes
Beautiful work!!

2023-05-22 01:57 UTC, jalbe0076 requested changes
please resolve merge conflicts

2023-05-22 01:57 UTC, jalbe0076 requested changes
please resolve merge conflicts

2023-05-22 13:01 UTC, merged