refactor so that there is only one h1 tag, the whats cookin title
jalbe0076/whats-cooking pull request #46
Opened 2023-05-31 01:30 UTC by alivaditis

### What is the feature?

This PR will close #45 
Changed html and dom manipulations so that there is only h1 tag on the page, the 'what's cookin' title
All other headings are h2 when appropriate

2023-05-31 13:47 UTC, jalbe0076 requested changes
h1 tags changing to h2 tags need some styling added onto them. Currently the text size is smaller than what we previously had.
<img width="1226" alt="image" src="https://github.com/jalbe0076/whats-cooking/assets/123283073/d100e4c8-e856-46ae-9192-310722e1e6f6">


Not sure if this is a bug created with the h2 tags but the circle changes to an oval depending on the browser width.
<img width="126" alt="image" src="https://github.com/jalbe0076/whats-cooking/assets/123283073/0296201a-0800-4419-a629-8facea50ded3">

2023-05-31 20:02 UTC, CaliHam requested changes

2023-05-31 20:56 UTC, CaliHam approved these changes

2023-06-01 14:41 UTC, jalbe0076 approved these changes
Looks great!

2023-06-01 14:42 UTC, paulina-isabel approved these changes

2023-06-01 14:43 UTC, merged